"""Regenerate README contacts from the runtime metadata (no hand-maintained copy)."""

import argparse
from pathlib import Path
from app_metadata import APP_METADATA

START = '<!-- app-metadata:start (generated by sync_app_metadata.py) -->'
END = '<!-- app-metadata:end -->'


def render_contacts():
    metadata = APP_METADATA
    return '\n'.join([
        START,
        '### Разработчик',
        '',
        f"Разработчик: {metadata['developer_name']}",
        '',
        f"[GitHub]({metadata['github_url']}) · "
        f"[Telegram]({metadata['telegram_url']}) · "
        f"[Email](mailto:{metadata['developer_email']})",
        END,
    ])


def sync_readme(check=False):
    path = Path(__file__).resolve().parent / 'README.md'
    source = path.read_text(encoding='utf-8')
    if START in source:
        before, remaining = source.split(START, 1)
        _, after = remaining.split(END, 1)
        updated = before + render_contacts() + after
    else:
        updated = source.rstrip() + '\n\n' + render_contacts() + '\n'
    if check:
        return source == updated
    path.write_text(updated, encoding='utf-8', newline='\n')
    return True


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    raise SystemExit(0 if sync_readme(parser.parse_args().check) else 1)
